rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        docker/*: ref-pin
        super-linter/*: ref-pin

ignore:
  - path: ".github/dependabot.yaml"
    rules: ["dependabot-cooldown"]
